var namespaceweb__scraping_1_1sofascore_1_1scraper_1_1ratings =
[
    [ "SofaScorePlayerStatsScraper", "classweb__scraping_1_1sofascore_1_1scraper_1_1ratings_1_1_sofa_score_player_stats_scraper.html", "classweb__scraping_1_1sofascore_1_1scraper_1_1ratings_1_1_sofa_score_player_stats_scraper" ]
];