var namespaceweb__scraping_1_1sofascore_1_1scraper_1_1players =
[
    [ "SofaScorePlayersScraper", "classweb__scraping_1_1sofascore_1_1scraper_1_1players_1_1_sofa_score_players_scraper.html", "classweb__scraping_1_1sofascore_1_1scraper_1_1players_1_1_sofa_score_players_scraper" ]
];