services:
  postgres:
    image: postgres:15
    container_name: iamscout_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: iamscout
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5434:5432"
    volumes:
      - ../../db/sql/schema.sql:/docker-entrypoint-initdb.d/001_schema.sql
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: