services:
  transform:
    build: .
    container_name: iamscout_transform
    volumes:
      - ${HOST_PROJECT_ROOT}/data:/data
      - ${HOST_PROJECT_ROOT}/ml_output:/output
      - ${HOST_PROJECT_ROOT}/containers/transform:/app/scripts
    working_dir: /app
    tty: true
    stdin_open: true
    environment:
      - PYTHONPATH=/app