services:
  transform:
    build: .
    container_name: iamscout_transform
    volumes:
      - ../../data:/data
      - ../../ml_output:/output
      - .:/app/scripts
    working_dir: /app
    tty: true
    stdin_open: true
    environment:
      - PYTHONPATH=/app
    networks:
      - iamscout_network

networks:
  iamscout_network:
    external: true
    name: database_default